"""Write lib/poseFrames.ts (figure bbox per exercise, union of both phases) from render sidecars.
usage: python3 make_manifest.py <raw_dir> <app_dir> <version>"""
import sys, json, glob, os
raw, app, ver = sys.argv[1], sys.argv[2], sys.argv[3]
frames = {}
for f in sorted(glob.glob(os.path.join(raw, "*-exec.png.json"))):
    m = json.load(open(f))
    if "bbox" in m:
        frames[os.path.basename(f)[:-len("-exec.png.json")]] = [round(v, 4) for v in m["bbox"]]
lines = ["// Generated by tools/3d/scripts/make_manifest.py. Do not edit by hand.",
         'import type { ExerciseSlug } from "@/lib/types";', "",
         "/** Bump when the renders change so browsers and the service worker fetch new files. */",
         f'export const POSE_VERSION = "{ver}";', "",
         "/** Figure bounding box [x0, y0, x1, y1] in normalised image coords, union of start and exec. */",
         "export const POSE_FRAMES: Partial<Record<ExerciseSlug, [number, number, number, number]>> = {"]
for k, v in frames.items():
    lines.append(f'  "{k}": [{", ".join(str(x) for x in v)}],')
lines += ["};", ""]
open(os.path.join(app, "lib", "poseFrames.ts"), "w").write("\n".join(lines))
print(len(frames), "frames")
