import type { Exercise, ExerciseSlug } from "./types";
export type { Exercise, ExerciseSlug } from "./types";

const V = "9";

function formPaths(slug: ExerciseSlug) {
  return {
    formStartImage: `/forms/${slug}-start.jpg?v=${V}`,
    formExecImage: `/forms/${slug}-exec.jpg?v=${V}`,
    formImage: `/forms/${slug}-exec.jpg?v=${V}`,
  };
}

export const EXERCISES: Exercise[] = [
  {
    slug: "planks",
    name: "Planks",
    emoji: "🧱",
    description: "Isometric core hold — build a rock-solid midline.",
    formCues: [
      "Elbows under shoulders, forearms flat on the floor.",
      "Body in one straight line from head to heels.",
      "Squeeze glutes and brace your midsection.",
      "Keep neck neutral — gaze slightly ahead of your hands.",
      "Breathe steadily; don't hold your breath.",
    ],
    ...formPaths("planks"),
    defaultSetDurationSec: 40,
    tracking: "timed",
  },
  {
    slug: "burpees",
    name: "Burpees",
    emoji: "🔥",
    description: "Full-body cardio blaster — squat, plank, jump.",
    formCues: [
      "Drop into a squat and plant hands on the floor.",
      "Jump or step feet back to a strong plank.",
      "Chest can kiss the floor, then push up.",
      "Jump feet forward under your hips.",
      "Explode up with a soft landing.",
      "Keep a smooth rhythm — quality over frantic speed.",
    ],
    ...formPaths("burpees"),
    defaultSetDurationSec: 45,
    tracking: "reps",
    defaultReps: 10,
  },
  {
    slug: "jogging",
    name: "Jogging",
    emoji: "🏃",
    description: "Steady-state cardio to build engine and endurance.",
    formCues: [
      "Land softly midfoot, not heavy on the heels.",
      "Keep a slight forward lean from the ankles.",
      "Relax shoulders; swing arms naturally.",
      "Breathe in a comfortable rhythmic pattern.",
      "Maintain an easy conversational pace for working sets.",
    ],
    ...formPaths("jogging"),
    defaultSetDurationSec: 90,
    tracking: "timed",
  },
  {
    slug: "dips",
    name: "Dips",
    emoji: "💪",
    description: "Triceps and chest pressing using a chair or parallel bars.",
    formCues: [
      "Hands on a sturdy surface, fingers forward.",
      "Lower with control until elbows are about 90°.",
      "Keep elbows tracking slightly back, not flaring wide.",
      "Press up by driving through your palms.",
      "Stay tall through the chest; avoid shrugging.",
    ],
    ...formPaths("dips"),
    defaultSetDurationSec: 40,
    tracking: "reps",
    defaultReps: 12,
  },
  {
    slug: "lunges",
    name: "Lunges",
    emoji: "🦵",
    description: "Unilateral leg strength and balance.",
    formCues: [
      "Step forward and lower until both knees bend ~90°.",
      "Front knee tracks over mid-foot, not past toes aggressively.",
      "Back knee floats just above the floor.",
      "Drive through the front heel to stand.",
      "Keep torso upright and core braced.",
      "Alternate legs or finish one side then the other.",
    ],
    ...formPaths("lunges"),
    defaultSetDurationSec: 45,
    tracking: "reps",
    defaultReps: 16,
  },
  {
    slug: "squats",
    name: "Squats",
    emoji: "🏋️",
    description: "Foundational lower-body strength mover.",
    formCues: [
      "Feet about shoulder-width, toes slightly out.",
      "Sit hips back and down like into a chair.",
      "Keep chest proud and heels planted.",
      "Knees track in line with toes.",
      "Stand by driving through midfoot and squeezing glutes.",
    ],
    ...formPaths("squats"),
    defaultSetDurationSec: 45,
    tracking: "reps",
    defaultReps: 15,
  },
  {
    slug: "push-ups",
    name: "Push-ups",
    emoji: "🫸",
    description: "Classic upper-body push for chest, shoulders, triceps.",
    formCues: [
      "Hands under shoulders, body in a rigid plank.",
      "Lower chest toward the floor with control.",
      "Elbows ~45° from your torso.",
      "Press up without sagging hips or piked butt.",
      "Modify on knees if needed — keep the same line.",
    ],
    ...formPaths("push-ups"),
    defaultSetDurationSec: 40,
    tracking: "reps",
    defaultReps: 12,
  },
  {
    slug: "sit-ups",
    name: "Sit-ups",
    emoji: "🧘",
    description: "Core flexion for abdominal endurance.",
    formCues: [
      "Lie on your back, knees bent, feet planted.",
      "Lightly support the head — don't yank the neck.",
      "Curl shoulders up using your abs, not momentum.",
      "Exhale on the way up; inhale on the way down.",
      "Control the descent — no collapsing.",
    ],
    ...formPaths("sit-ups"),
    defaultSetDurationSec: 40,
    tracking: "reps",
    defaultReps: 15,
  },
  {
    slug: "skull-crushers",
    name: "Skull Crushers",
    emoji: "🦾",
    description: "Triceps isolation — use light dumbbells or a water bottle.",
    formCues: [
      "Lie on your back, arms extended above the chest.",
      "Keep upper arms still; bend only at the elbows.",
      "Lower weight toward forehead / behind head with control.",
      "Extend elbows to lock out without slamming.",
      "Use a weight you can control for every rep.",
    ],
    ...formPaths("skull-crushers"),
    defaultSetDurationSec: 40,
    tracking: "reps",
    defaultReps: 12,
  },
  {
    slug: "downward-dog",
    name: "Downward Dog",
    emoji: "🔺",
    description: "Timed yoga hold — hips high, long spine, heels reaching.",
    formCues: [
      "Start with hands on the floor, shoulder-width, knees soft.",
      "Lift your hips up and back so the body makes a long inverted V.",
      "Press the floor away and keep the neck relaxed.",
      "Heels reach toward the mat; a bend in the knees is fine.",
      "Breathe steadily and hold. Don't dump weight into the shoulders.",
    ],
    ...formPaths("downward-dog"),
    defaultSetDurationSec: 40,
    tracking: "timed",
  },
  {
    slug: "warrior",
    name: "Warrior",
    emoji: "🏹",
    description: "Timed warrior hold — strong legs, open chest, steady gaze.",
    formCues: [
      "Stand tall, feet wide, arms relaxed out to the sides.",
      "Bend the front knee over the ankle; back leg stays long.",
      "Hips open to the side, chest proud, shoulders down.",
      "Front knee tracks over the middle of the foot.",
      "Breathe and hold. Don't let the front knee cave in.",
    ],
    ...formPaths("warrior"),
    defaultSetDurationSec: 40,
    tracking: "timed",
  },
  {
    slug: "childs-pose",
    name: "Child's Pose",
    emoji: "🧎",
    description: "Timed rest hold — hips to heels, arms long, easy breath.",
    formCues: [
      "Kneel tall, knees apart or together, tops of the feet down.",
      "Fold the hips back toward the heels and walk the hands forward.",
      "Forehead rests on the mat or a fist if the neck needs space.",
      "Let the belly soften between the thighs.",
      "Breathe into the back. Don't force the hips down.",
    ],
    ...formPaths("childs-pose"),
    defaultSetDurationSec: 40,
    tracking: "timed",
  },
  {
    slug: "cobra",
    name: "Cobra",
    emoji: "🐍",
    description: "Timed backbend hold — chest lifts, hips stay heavy.",
    formCues: [
      "Lie face-down, hands under the shoulders, legs long.",
      "Press the tops of the feet down and lift the chest.",
      "Elbows stay slightly bent and hug in, not locked wide.",
      "Hips and legs stay on the floor. Lead with the chest, not the chin.",
      "Breathe and hold. Come down if the low back pinches.",
    ],
    ...formPaths("cobra"),
    defaultSetDurationSec: 40,
    tracking: "timed",
  },
  {
    slug: "hip-flexor",
    name: "Hip Flexor Stretch",
    emoji: "🦵",
    description: "Timed half-kneeling hold for the front of the hip.",
    formCues: [
      "Kneel on one knee, other foot forward, torso tall.",
      "Tuck the pelvis slightly and shift the hips forward.",
      "Feel the stretch on the kneeling side, front of the hip.",
      "Keep the front knee over the ankle, not past it.",
      "Breathe and hold. Switch sides. Don't arch the low back.",
    ],
    ...formPaths("hip-flexor"),
    defaultSetDurationSec: 40,
    tracking: "timed",
  },
  {
    slug: "hamstring",
    name: "Hamstring Stretch",
    emoji: "🦶",
    description: "Timed deeper hamstring hold — one leg long, hips square.",
    formCues: [
      "Stand tall beside a wall or counter for balance.",
      "Rest one heel up and keep that knee as straight as you can.",
      "Hinge from the hips toward the raised leg, back long.",
      "The standing knee stays soft. Hips stay square.",
      "Breathe and hold. Switch sides. Don't bounce or round hard.",
    ],
    ...formPaths("hamstring"),
    defaultSetDurationSec: 40,
    tracking: "timed",
  },
  {
    slug: "chest-opener",
    name: "Chest Opener",
    emoji: "🫁",
    description: "Timed chest hold — open the front of the shoulders.",
    formCues: [
      "Stand tall and open the arms out to the sides.",
      "Lift the chest and draw the shoulder blades gently together.",
      "If you're on your back, press through the feet and open the chest.",
      "Keep the neck long. Ribs stay down, not flared.",
      "Breathe into the chest and hold. Don't pinch the low back.",
    ],
    ...formPaths("chest-opener"),
    defaultSetDurationSec: 40,
    tracking: "timed",
  },
  {
    slug: "shoulder-stretch",
    name: "Shoulder Stretch",
    emoji: "🙆",
    description: "Timed overhead shoulder hold — ribs in, arms long.",
    formCues: [
      "Stand tall, feet under the hips, shoulders relaxed.",
      "Reach both arms overhead, palms facing or lightly touching.",
      "Lengthen through the sides of the waist.",
      "Keep the ribs down so the low back doesn't crank.",
      "Breathe and hold. Ease off if a shoulder pinches.",
    ],
    ...formPaths("shoulder-stretch"),
    defaultSetDurationSec: 40,
    tracking: "timed",
  },
  {
    slug: "quad-stretch",
    name: "Quad Stretch",
    emoji: "🦿",
    description: "Timed standing quad hold — heel to hip, knees together.",
    formCues: [
      "Stand tall and hold a wall if you need balance.",
      "Bend one knee and catch the ankle or shoe behind you.",
      "Knees stay close. Hips point forward, not turned out.",
      "Gently draw the heel toward the hip without leaning way forward.",
      "Breathe and hold. Switch sides. Don't yank the knee.",
    ],
    ...formPaths("quad-stretch"),
    defaultSetDurationSec: 40,
    tracking: "timed",
  },
  {
    slug: "calf-stretch",
    name: "Calf Stretch",
    emoji: "👟",
    description: "Timed wall calf hold — heel down, back leg long.",
    formCues: [
      "Stand facing a wall, hands on it, one foot back.",
      "Keep the back heel down and the back knee straight.",
      "Lean the hips toward the wall until the calf wakes up.",
      "Toes point forward. The front knee stays soft.",
      "Breathe and hold. Switch sides. Don't let the heel pop up.",
    ],
    ...formPaths("calf-stretch"),
    defaultSetDurationSec: 40,
    tracking: "timed",
  },
];

export function getExercise(slug: string): Exercise | undefined {
  return EXERCISES.find((e) => e.slug === slug);
}

export function isValidSlug(slug: string): slug is ExerciseSlug {
  return EXERCISES.some((e) => e.slug === slug);
}

/** Build a tight one-way coaching script from form cues + benefits framing. */
export { buildFormCoachScript } from "./coach";

export const DISCLAIMER =
  "Not medical advice. Consult a professional before starting any exercise program. Stop immediately if you feel pain, dizziness, or unusual discomfort.";
