// Generated by tools/3d/scripts/make_manifest.py. Do not edit by hand.
import type { ExerciseSlug } from "@/lib/types";

/** Bump when the renders change so browsers and the service worker fetch new files. */
export const POSE_VERSION = "3d1";

/** Figure bounding box [x0, y0, x1, y1] in normalised image coords, union of start and exec. */
export const POSE_FRAMES: Partial<Record<ExerciseSlug, [number, number, number, number]>> = {
  "burpees": [0.07, 0.212, 0.93, 0.848],
  "calf-stretch": [0.07, 0.1526, 0.93, 0.9074],
  "chest-opener": [0.07, 0.2021, 0.93, 0.8579],
  "childs-pose": [0.07, 0.265, 0.93, 0.795],
  "cobra": [0.05, 0.4153, 0.95, 0.7847],
  "dips": [0.07, 0.2324, 0.93, 0.8276],
  "downward-dog": [0.07, 0.2348, 0.93, 0.8252],
  "hamstring": [0.07, 0.1979, 0.93, 0.8621],
  "hip-flexor": [0.07, 0.1943, 0.93, 0.8657],
  "jogging": [0.07, 0.1574, 0.93, 0.9026],
  "lunges": [0.1149, 0.11, 0.8851, 0.95],
  "planks": [0.05, 0.4854, 0.95, 0.7146],
  "push-ups": [0.05, 0.479, 0.95, 0.721],
  "quad-stretch": [0.2423, 0.11, 0.7577, 0.95],
  "shoulder-stretch": [0.2382, 0.11, 0.7618, 0.95],
  "sit-ups": [0.05, 0.366, 0.95, 0.834],
  "skull-crushers": [0.07, 0.332, 0.93, 0.728],
  "squats": [0.07, 0.1714, 0.93, 0.8886],
  "warrior": [0.07, 0.2569, 0.93, 0.8031],
};
